### ISSUE TITLE
Quel est l'objectif du projet?

### ISSUE THREAD

**Issue by pascalfares** [projets2017cl/WorkflowProject#1]
Quel en sera le résultat?

Amélioration jbpm? 

nouvelle fonctions?

intégration ailleur.

Besoin de clarifications

**Comment by t-g-tannous** [comment]
Le resultat est d'avoir un produit(  une application Web) , avec un web Workflow designer qui nous permet a partir de l'application de creer le workflow qui sera integrer avec le moteur de workflow JBPM . Non il n'y aura pas d'amelioration en principe sur JBPM au niveau du moteur , par contre il y aura par exemple la possibilite d'envoyer  un sms ou mail qui seront de type d'actions de taches.
Merci

**Comment by t-g-tannous** [comment]
est ce que tu  as besoin de plus d'information ou je peux cloturer ce ticket?

**Comment by pascalfares** [comment]
OK
