### ISSUE TITLE
Architecture Documentation + Application Design

### ISSUE THREAD

**Issue by t-g-tannous** [projets2017cl/WorkflowProject#3]

**Comment by pascalfares** [comment]
Est ce que c'est fini cette tâche

**Comment by t-g-tannous** [comment]
Il faut que je termine la doc pour fin de semaine

**Comment by t-g-tannous** [comment]
[Workflow Engine - Document architecture technique 1.0.docx](https://github.com/projets2017cl/WorkflowProject/files/1236464/Workflow.Engine.-.Document.architecture.technique.1.0.docx)
Bonjour @pascalfares 

Voici le document d'architecture , surement si jamais il y a quelqu'un qui veux ajouter d'autre idee sans probleme :)
